blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/linguijs/i18n/discussions/new?category=ideas
    about: 'For ideas or feature requests, start a new discussion'
  - name: Support Questions & Other
    url: https://github.com/linguijs/i18n/discussions/new?category=help
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
